/**
 * The contract between a host and a module it frames.
 *
 * Shapes, and nothing else. Everything exported here is a type, a schema, a
 * constant, or a pure function over one of those. Nothing in this package reads
 * a file, opens a socket, holds state, or decides anything — see the README for
 * why that rule is load-bearing rather than tidy.
 */

export {
  PROTOCOL,
  WELL_KNOWN,
  LEGACY_WELL_KNOWN,
  MANIFEST_KIND,
  LEGACY_MANIFEST_KIND,
  MESSAGE,
  MESSAGE_PREFIX,
  LEGACY_MESSAGE_PREFIX,
  MESSAGE_PREFIXES,
  HOST_MESSAGES,
  MODULE_MESSAGES,
  MIN_HEIGHT,
  MAX_HEIGHT,
  REFRESH_EVERY_MIN,
  REFRESH_EVERY_MAX,
  clampHeight,
  LIMITS,
  type MessageType,
} from './constants.js'

export { MODULE_ID, MODE_ID, EPIC_SLUG, own, slugFrom } from './ids.js'

export {
  DIALECTS,
  canonicalName,
  legacyName,
  nameIn,
  canonicalModuleId,
  legacyModuleId,
  canonicalExtension,
  dialectOfType,
  dialectOfKind,
  toDialect,
  canonicalMessage,
  type Dialect,
} from './dialect.js'

export {
  KEHIKOT_DIR,
  DATA_FILE,
  MODULE_FOLDER,
  KEHIKOT_IGNORE,
  moduleFolder,
  kehikotDir,
  moduleDir,
  moduleFile,
  within,
  ignoresKehikot,
  withKehikotIgnored,
  withoutKehikotIgnored,
} from './project.js'

export {
  manifestSchema,
  legacyManifest,
  speaks,
  partsDeclaration,
  MODULE_CONDITIONS,
  REACTS_TO,
  REACTION_NAMES,
  TAGS,
  TAG_NAMES,
  type Reaction,
  type Tag,
  type Manifest,
  type ManifestInput,
  type ModuleMode,
  type ModuleCondition,
} from './manifest.js'

export {
  CAPABILITIES,
  CAPABILITY_NAMES,
  METHODS,
  METHOD_NAMES,
  methodParams,
  methodResults,
  resultSchemaFor,
  navigationResult,
  NAVIGATION_OUTCOMES,
  projectPickResult,
  pickedProject,
  PICK_OUTCOMES,
  epicSpine,
  epicsListResult,
  REPORTED_STAGES,
  type Capability,
  type Method,
  type MethodParams,
  type NavigationOutcome,
  type NavigationResult,
  type PickOutcome,
  type PickedProject,
  type ProjectPickResult,
  type EpicSpine,
  type EpicsListResult,
  type ReportedStage,
} from './methods.js'

export {
  contextSchema,
  passageSchema,
  sectionSchema,
  showingSchema,
  containerSchema,
  helloSchema,
  contextMessageSchema,
  responseSchema,
  responseFailureReasons,
  gotoSchema,
  eventSchema,
  readySchema,
  requestSchema,
  resizeSchema,
  wentSchema,
  filtersSchema,
  filterGroupSchema,
  filterOptionSchema,
  filterChoiceSchema,
  dispositionSchema,
  DISPOSITIONS,
  clearableSchema,
  clearSchema,
  refreshableSchema,
  refreshSchema,
  hostMessageSchema,
  moduleMessageSchema,
  looksLikeWireMessage,
  type ModuleContext,
  type Passage,
  type Section,
  type Showing,
  type CanvasContainer,
  type ResponseFailureReason,
  type HostMessage,
  type ModuleMessage,
  type WireMessage,
  type Hello,
  type ContextMessage,
  type Response,
  type Goto,
  type ModuleEvent,
  type Ready,
  type Request,
  type Resize,
  type Went,
  type Filters,
  type FilterGroup,
  type FilterOption,
  type FilterChoice,
  type Disposition,
  type DispositionValue,
  type Clearable,
  type Clear,
  type Refreshable,
  type Refresh,
} from './wire.js'

export {
  TRACKERS,
  TRACKER_KINDS,
  TRACKER_STATES,
  TRACKER_DETAILS,
  PIPELINE_STATES,
  REVIEW_STATES,
  LINK_RELATIONS,
  MISSING_REASONS,
  REFRESH_OUTCOMES,
  TRACKER_REFRESH_WITHIN_MS,
  trackerRowSchema,
  trackerLinkSchema,
  trackerFileSchema,
  trackerDetailSchema,
  trackerSourceSchema,
  trackerMissingSchema,
  trackerReadingResult,
  trackerRefreshResult,
  trackerSignalSchema,
  readTrackerRef,
  spellTrackerRef,
  type Tracker,
  type TrackerDetail,
  type PipelineState,
  type ReviewState,
  type LinkRelation,
  type TrackerLink,
  type TrackerFile,
  type TrackerDetailFacts,
  type TrackerRow,
  type TrackerSource,
  type MissingReason,
  type TrackerMissing,
  type TrackerReading,
  type RefreshOutcome,
  type TrackerRefreshResult,
  type TrackerSignal,
  type TrackerRefName,
} from './tracker.js'

export {
  PART_ID,
  partSchema,
  partsSchema,
  pickedParts,
  isFocused,
  refInFocus,
  partInFocus,
  focusCount,
  PAPER_MODULE,
  partFile,
  isPartFile,
  paperFileOf,
  partsOfFile,
  pickedFiles,
  fileInFocus,
  anchorInFocus,
  narrowToFocus,
  focusSentence,
  FOCUS_WHERE,
  sameParts,
  type EpicPart,
  type Anchor,
  type Anchors,
  type Narrowed,
} from './parts.js'

export {
  JOURNEYS_MODULE,
  JOURNEYS_FILE,
  journeyStepSchema,
  journeyGroupSchema,
  stepsFromSchema,
  journeyRecordSchema,
  journeysDocumentSchema,
  journeyIn,
  journeySlugs,
  stepsOf,
  stepPart,
  partIdsOf,
  partsOf,
  type JourneyPart,
  type JourneyStep,
  type JourneyGroup,
  type StepsFrom,
  type JourneyRecord,
  type JourneysDocument,
  type JourneySteps,
} from './journey.js'

export {
  CONTENT_HOST,
  contentChangeSchema,
  contentSignalSchema,
  contentStamp,
  type ContentChange,
  type ContentSignal,
} from './content.js'

export {
  notificationPayload,
  callPayload,
  EXTENSIONS,
  EXTENSION_NAMES,
  known,
  schemaFor,
  type NotificationPayload,
  type CallPayload,
  type ExtensionFormat,
} from './extensions.js'

export {
  CITE_STATUSES,
  CITE_MARKER,
  parseSource,
  serialiseSource,
  uncitable,
  markersIn,
  replaceMarkers,
  normaliseQuote,
  findQuote,
  resolveSource,
  linesOf,
  type CitedSource,
  type CiteStatus,
  type CitedRange,
  type CitationView,
  type MarkerScan,
} from './citations.js'
